# Generated by Django 6.0 on 2025-12-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=50)),
                ('dream_job', models.CharField(max_length=100)),
                ('twelfth_group', models.CharField(max_length=50)),
            ],
        ),
    ]
