# Generated by Django 6.0 on 2025-12-22 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_career_degree_preparationstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('cutoff', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Government', 'Government'), ('Private', 'Private')], max_length=50)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colleges', to='api.degree')),
            ],
        ),
    ]
