# Generated by Django 6.0 on 2025-12-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_userprofile_photo_college_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='college_selected',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='degree_selected',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preparation_started',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_completed',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='selected_college',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='selected_degree',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.TextField(blank=True),
        ),
    ]
