# Generated by Django 6.0 on 2025-12-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userprofile_college_selected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='degree',
        ),
        migrations.AddField(
            model_name='college',
            name='degrees',
            field=models.ManyToManyField(related_name='colleges', to='api.degree'),
        ),
    ]
