# Generated by Django 6.0 on 2025-12-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_college_degree_college_degrees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='cutoff',
        ),
        migrations.RemoveField(
            model_name='college',
            name='location',
        ),
        migrations.AlterField(
            model_name='college',
            name='type',
            field=models.CharField(choices=[('Government', 'Government'), ('Private', 'Private')], default='Private', max_length=50),
        ),
    ]
