# Generated by Django 6.0 on 2025-12-24 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_college_cutoff_remove_college_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.career'),
        ),
    ]
